print("Anggota Kelompok 3")
print("1. Rafi Fadhila Ramadhani")
print("2. Enrike Manurung")
print("3. Diana Permatasari")
print("4. Vella Kharisma Pransisca")
print("5. Ratu Keisha Laila Rahmadita")
print("6. Anjelika Maulida")